,ref_no_slash,file_path,exception_str
0,datasnaek_youtube-new,../datasets\datasnaek_youtube-new\JPvideos.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 501, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 321, in create_profiler_report
    sample_size = min(len(data.data), 500000)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 597, in _load_data_from_file
    return data_utils.read_csv_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 324, in read_csv_df
    data = fo.read()
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py"", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File ""pandas\_libs\parsers.pyx"", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File ""pandas\_libs\parsers.pyx"", line 890, in pandas._libs.parsers.TextReader._read_rows
  File ""pandas\_libs\parsers.pyx"", line 1037, in pandas._libs.parsers.TextReader._convert_column_data
  File ""pandas\_libs\parsers.pyx"", line 1068, in pandas._libs.parsers.TextReader._convert_tokens
  File ""pandas\_libs\parsers.pyx"", line 1230, in pandas._libs.parsers.TextReader._convert_with_dtype
  File ""pandas\_libs\parsers.pyx"", line 1246, in pandas._libs.parsers.TextReader._string_convert
  File ""pandas\_libs\parsers.pyx"", line 1444, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 253-254: unexpected end of data
"
1,datasnaek_youtube-new,../datasets\datasnaek_youtube-new\KRvideos.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 501, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 321, in create_profiler_report
    sample_size = min(len(data.data), 500000)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 597, in _load_data_from_file
    return data_utils.read_csv_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 324, in read_csv_df
    data = fo.read()
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py"", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File ""pandas\_libs\parsers.pyx"", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File ""pandas\_libs\parsers.pyx"", line 866, in pandas._libs.parsers.TextReader._read_rows
  File ""pandas\_libs\parsers.pyx"", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File ""pandas\_libs\parsers.pyx"", line 1965, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 261291-261292: invalid continuation byte
"
2,datasnaek_youtube-new,../datasets\datasnaek_youtube-new\MXvideos.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 501, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 321, in create_profiler_report
    sample_size = min(len(data.data), 500000)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 597, in _load_data_from_file
    return data_utils.read_csv_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 324, in read_csv_df
    data = fo.read()
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py"", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File ""pandas\_libs\parsers.pyx"", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File ""pandas\_libs\parsers.pyx"", line 866, in pandas._libs.parsers.TextReader._read_rows
  File ""pandas\_libs\parsers.pyx"", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File ""pandas\_libs\parsers.pyx"", line 1965, in pandas._libs.parsers.raise_parser_error
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc3 in position 130670: invalid continuation byte
"
3,datasnaek_youtube-new,../datasets\datasnaek_youtube-new\RUvideos.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 501, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 321, in create_profiler_report
    sample_size = min(len(data.data), 500000)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 597, in _load_data_from_file
    return data_utils.read_csv_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 324, in read_csv_df
    data = fo.read()
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py"", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File ""pandas\_libs\parsers.pyx"", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File ""pandas\_libs\parsers.pyx"", line 890, in pandas._libs.parsers.TextReader._read_rows
  File ""pandas\_libs\parsers.pyx"", line 1037, in pandas._libs.parsers.TextReader._convert_column_data
  File ""pandas\_libs\parsers.pyx"", line 1068, in pandas._libs.parsers.TextReader._convert_tokens
  File ""pandas\_libs\parsers.pyx"", line 1230, in pandas._libs.parsers.TextReader._convert_with_dtype
  File ""pandas\_libs\parsers.pyx"", line 1246, in pandas._libs.parsers.TextReader._string_convert
  File ""pandas\_libs\parsers.pyx"", line 1444, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd0 in position 254: unexpected end of data
"
4,rashikrahmanpritom_heart-attack-analysis-prediction-dataset,../datasets\rashikrahmanpritom_heart-attack-analysis-prediction-dataset\o2Saturation.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 501, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 321, in create_profiler_report
    sample_size = min(len(data.data), 500000)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 597, in _load_data_from_file
    return data_utils.read_csv_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 324, in read_csv_df
    data = fo.read()
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py"", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File ""pandas\_libs\parsers.pyx"", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File ""pandas\_libs\parsers.pyx"", line 866, in pandas._libs.parsers.TextReader._read_rows
  File ""pandas\_libs\parsers.pyx"", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File ""pandas\_libs\parsers.pyx"", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 2 fields in line 1356, saw 3

"
5,uciml_breast-cancer-wisconsin-data,../datasets\uciml_breast-cancer-wisconsin-data\data.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
6,rounakbanik_the-movies-dataset,../datasets\rounakbanik_the-movies-dataset\credits.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 339, in create_attributes_from_file_report
    add_consistency_attributes(attributes_dict, feature_stats, global_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 171, in add_consistency_attributes
    if feature_stats['data_type'] == 'integer':
TypeError: string indices must be integers
"
7,rounakbanik_the-movies-dataset,../datasets\rounakbanik_the-movies-dataset\keywords.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 339, in create_attributes_from_file_report
    add_consistency_attributes(attributes_dict, feature_stats, global_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 171, in add_consistency_attributes
    if feature_stats['data_type'] == 'integer':
TypeError: string indices must be integers
"
8,jealousleopard_goodreadsbooks,../datasets\jealousleopard_goodreadsbooks\books.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 501, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 321, in create_profiler_report
    sample_size = min(len(data.data), 500000)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 597, in _load_data_from_file
    return data_utils.read_csv_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 324, in read_csv_df
    data = fo.read()
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py"", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File ""pandas\_libs\parsers.pyx"", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File ""pandas\_libs\parsers.pyx"", line 866, in pandas._libs.parsers.TextReader._read_rows
  File ""pandas\_libs\parsers.pyx"", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File ""pandas\_libs\parsers.pyx"", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 12 fields in line 3350, saw 13

"
9,gpreda_reddit-vaccine-myths,../datasets\gpreda_reddit-vaccine-myths\reddit_vm.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 339, in create_attributes_from_file_report
    add_consistency_attributes(attributes_dict, feature_stats, global_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 171, in add_consistency_attributes
    if feature_stats['data_type'] == 'integer':
TypeError: string indices must be integers
"
10,muratkokludataset_acoustic-extinguisher-fire-dataset,../datasets\muratkokludataset_acoustic-extinguisher-fire-dataset\Acoustic_Extinguisher_Fire_Dataset\Acoustic_Extinguisher_Fire_Dataset.xlsx,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 496, in extract_file_attributes_to_df
    data = Data(file)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data.py"", line 76, in __new__
    data is not None or data_class.is_match(input_file_path, options_copy)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\graph_data.py"", line 155, in is_match
    if not CSVData.is_match(file_path, options):
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 643, in is_match
    data_as_str = data_utils.load_as_str_from_file(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 641, in load_as_str_from_file
    sample_lines = csvfile.read(sample_size_bytes)
  File ""C:\ProgramData\Anaconda3\lib\codecs.py"", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xaa in position 14: invalid start byte
"
11,himanshupoddar_zomato-bangalore-restaurants,../datasets\himanshupoddar_zomato-bangalore-restaurants\zomato.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 501, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 323, in create_profiler_report
    profile = Profiler(data, samples_per_update=sample_size, options=profiler_options)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\profilers\profile_builder.py"", line 2804, in __new__
    return UnstructuredProfiler(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\profilers\profile_builder.py"", line 1161, in __init__
    self.update_profile(data)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\profilers\profile_builder.py"", line 908, in update_profile
    self._update_profile_from_chunk(data, sample_size, min_true_samples)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\profilers\profile_builder.py"", line 1447, in _update_profile_from_chunk
    self._profile = UnstructuredCompiler(data, options=self.options, pool=pool)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\profilers\column_profile_compilers.py"", line 51, in __init__
    self._create_profile(df_series, options, pool)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\profilers\column_profile_compilers.py"", line 107, in _create_profile
    self.update_profile(df_series, pool)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\profilers\column_profile_compilers.py"", line 177, in update_profile
    self._profiles[profile_type].update(df_series)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\profilers\unstructured_labeler_profile.py"", line 197, in update
    self._update_helper(df_series, profile)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\profilers\utils.py"", line 681, in wrapper
    result = method(self, *args, **kw)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\profilers\unstructured_labeler_profile.py"", line 167, in _update_helper
    predictions = self.data_labeler.predict(df_series_clean)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\labelers\base_data_labeler.py"", line 315, in predict
    results = self._model.predict(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\labelers\character_level_cnn_model.py"", line 844, in predict
    predictions_list[index] = list(predictions[index][:sentence_length])
MemoryError
"
12,austinreese_craigslist-carstrucks-data,../datasets\austinreese_craigslist-carstrucks-data\vehicles.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
13,kazanova_sentiment140,../datasets\kazanova_sentiment140\training.1600000.processed.noemoticon.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 501, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 321, in create_profiler_report
    sample_size = min(len(data.data), 500000)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 597, in _load_data_from_file
    return data_utils.read_csv_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 324, in read_csv_df
    data = fo.read()
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py"", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File ""pandas\_libs\parsers.pyx"", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File ""pandas\_libs\parsers.pyx"", line 890, in pandas._libs.parsers.TextReader._read_rows
  File ""pandas\_libs\parsers.pyx"", line 1037, in pandas._libs.parsers.TextReader._convert_column_data
  File ""pandas\_libs\parsers.pyx"", line 1068, in pandas._libs.parsers.TextReader._convert_tokens
  File ""pandas\_libs\parsers.pyx"", line 1230, in pandas._libs.parsers.TextReader._convert_with_dtype
  File ""pandas\_libs\parsers.pyx"", line 1246, in pandas._libs.parsers.TextReader._string_convert
  File ""pandas\_libs\parsers.pyx"", line 1444, in pandas._libs.parsers._string_box_utf8
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 80-81: invalid continuation byte
"
14,kashnitsky_mlcourse,../datasets\kashnitsky_mlcourse\wiki_machine_learning.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 501, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 321, in create_profiler_report
    sample_size = min(len(data.data), 500000)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\structured_mixins.py"", line 60, in _load_data
    self._data = self._load_data_from_file(self.input_file_path)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 597, in _load_data_from_file
    return data_utils.read_csv_df(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 324, in read_csv_df
    data = fo.read()
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\readers.py"", line 1778, in read
    ) = self._engine.read(  # type: ignore[attr-defined]
  File ""C:\ProgramData\Anaconda3\lib\site-packages\pandas\io\parsers\c_parser_wrapper.py"", line 230, in read
    chunks = self._reader.read_low_memory(nrows)
  File ""pandas\_libs\parsers.pyx"", line 808, in pandas._libs.parsers.TextReader.read_low_memory
  File ""pandas\_libs\parsers.pyx"", line 866, in pandas._libs.parsers.TextReader._read_rows
  File ""pandas\_libs\parsers.pyx"", line 852, in pandas._libs.parsers.TextReader._tokenize_rows
  File ""pandas\_libs\parsers.pyx"", line 1973, in pandas._libs.parsers.raise_parser_error
pandas.errors.ParserError: Error tokenizing data. C error: Expected 7 fields in line 2, saw 8

"
15,piterfm_2022-ukraine-russian-war,../datasets\piterfm_2022-ukraine-russian-war\russia_losses_equipment_correction.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 339, in create_attributes_from_file_report
    add_consistency_attributes(attributes_dict, feature_stats, global_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 171, in add_consistency_attributes
    if feature_stats['data_type'] == 'integer':
TypeError: string indices must be integers
"
16,rohanrao_nifty50-stock-market-data,../datasets\rohanrao_nifty50-stock-market-data\INFRATEL.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 339, in create_attributes_from_file_report
    add_consistency_attributes(attributes_dict, feature_stats, global_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 171, in add_consistency_attributes
    if feature_stats['data_type'] == 'integer':
TypeError: string indices must be integers
"
17,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\Canada_Hosp_COVID19_Inpatient_DatasetDefinitions\Canada_Hosp1_COVID_InpatientData.xlsx,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 496, in extract_file_attributes_to_df
    data = Data(file)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data.py"", line 76, in __new__
    data is not None or data_class.is_match(input_file_path, options_copy)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\graph_data.py"", line 155, in is_match
    if not CSVData.is_match(file_path, options):
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 643, in is_match
    data_as_str = data_utils.load_as_str_from_file(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 641, in load_as_str_from_file
    sample_lines = csvfile.read(sample_size_bytes)
  File ""C:\ProgramData\Anaconda3\lib\codecs.py"", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xba in position 10: invalid start byte
"
18,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\Canada_Hosp_COVID19_Inpatient_DatasetDefinitions\Canada_Hosp2_COVID_InpatientData.xlsx,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 496, in extract_file_attributes_to_df
    data = Data(file)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data.py"", line 76, in __new__
    data is not None or data_class.is_match(input_file_path, options_copy)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\graph_data.py"", line 155, in is_match
    if not CSVData.is_match(file_path, options):
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 643, in is_match
    data_as_str = data_utils.load_as_str_from_file(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 641, in load_as_str_from_file
    sample_lines = csvfile.read(sample_size_bytes)
  File ""C:\ProgramData\Anaconda3\lib\codecs.py"", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 10: invalid start byte
"
19,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\RDSC-07-30-Update\RDSC-07-30-Update\coders_against_covid\crowd-sourced-covid-19-testing-locations.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
20,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\RDSC-07-30-Update\RDSC-07-30-Update\covid_19_canada_open_data_working_group\public-covid-19-cases-canada.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
"
21,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\RDSC-07-30-Update\RDSC-07-30-Update\covid_tracking_project\covid-sources-for-counties.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
22,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\RDSC-07-30-Update\RDSC-07-30-Update\covid_tracking_project\covid-sources-for-us-states.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
"
23,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\RDSC-07-30-Update\RDSC-07-30-Update\covid_tracking_project\covid-statistics-by-us-states-daily-updates.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
24,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\RDSC-07-30-Update\RDSC-07-30-Update\covid_tracking_project\covid-statistics-by-us-states-totals.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
25,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\RDSC-07-30-Update\RDSC-07-30-Update\github\crowd-sourced-covid-19-testing-locations.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
26,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\RDSC-07-30-Update\RDSC-07-30-Update\HDE\acaps-covid-19-government-measures-dataset.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
27,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\RDSC-07-30-Update\RDSC-07-30-Update\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-country.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
28,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\RDSC-07-30-Update\RDSC-07-30-Update\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-over-time.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
29,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\RDSC-07-30-Update\RDSC-07-30-Update\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
30,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\RDSC-07-30-Update\RDSC-07-30-Update\ontario_government\confirmed-positive-cases-of-covid-19-in-ontario.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
31,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\canadian_outbreak_tracker\canada-enriched-population-case-data-by-province.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
32,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\coders_against_covid\crowd-sourced-covid-19-testing-locations.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
33,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\county_health_rankings\county_health_rankings\us-county-health-rankings-2020.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
34,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\covid_19_canada_open_data_working_group\public-covid-19-cases-canada.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
"
35,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\covid_tracking_project\covid-sources-for-counties.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
36,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\covid_tracking_project\covid-statistics-for-all-us-totals.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 339, in create_attributes_from_file_report
    add_consistency_attributes(attributes_dict, feature_stats, global_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 171, in add_consistency_attributes
    if feature_stats['data_type'] == 'integer':
TypeError: string indices must be integers
"
37,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\ECDC\current-data-on-the-geographic-distribution-of-covid-19-cases-worldwide.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
"
38,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\einstein\diagnosis-of-covid-19-and-its-clinical-spectrum.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
39,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\HDE\acaps-covid-19-government-measures-dataset.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
40,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\hifld\hifld\aircraft-landing-facilities.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
41,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\hifld\hifld\local-emergency-operations-centers-eoc.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
42,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\hifld\hifld\public-health-departments.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
43,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\hifld\hifld\urgent-care-facilities.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
44,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\hifld\hifld\us-ports-of-entry.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
45,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\johns_hopkins_csse\2019-novel-coronavirus-covid-19-2019-ncov-data-repository-confirmed-deaths-in-the-us.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
46,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-country.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
47,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-over-time.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
48,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
49,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\us_cdc\us_cdc\nutrition-physical-activity-and-obesity-behavioral-risk-factor-surveillance-system.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
50,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER\us_cdc\us_cdc\u-s-chronic-disease-indicators-cdi.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
51,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER_v4\UNCOVER\canadian_outbreak_tracker\canada-enriched-population-case-data-by-province.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
52,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER_v4\UNCOVER\coders_against_covid\crowd-sourced-covid-19-testing-locations.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
53,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER_v4\UNCOVER\covid_19_canada_open_data_working_group\public-covid-19-cases-canada.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'int' and 'NoneType'
"
54,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER_v4\UNCOVER\covid_tracking_project\covid-sources-for-counties.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
55,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER_v4\UNCOVER\covid_tracking_project\covid-statistics-for-all-us-daily-updates.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
56,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER_v4\UNCOVER\covid_tracking_project\covid-statistics-for-all-us-totals.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
57,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER_v4\UNCOVER\HDE\HDE\acaps-covid-19-government-measures-dataset.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
58,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER_v4\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-by-country.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
59,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER_v4\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases-over-time.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
60,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER_v4\UNCOVER\johns_hopkins_csse\johns-hopkins-covid-19-daily-dashboard-cases.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
61,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER_v4\UNCOVER\ontario_government\confirmed-positive-cases-of-covid-19-in-ontario.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
62,roche-data-science-coalition_uncover,../datasets\roche-data-science-coalition_uncover\UNCOVER_v4\UNCOVER\self_care_catalysts\self_care_catalysts\Kaggle App data dictionary.xlsx,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 496, in extract_file_attributes_to_df
    data = Data(file)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data.py"", line 76, in __new__
    data is not None or data_class.is_match(input_file_path, options_copy)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\graph_data.py"", line 155, in is_match
    if not CSVData.is_match(file_path, options):
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\csv_data.py"", line 643, in is_match
    data_as_str = data_utils.load_as_str_from_file(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 641, in load_as_str_from_file
    sample_lines = csvfile.read(sample_size_bytes)
  File ""C:\ProgramData\Anaconda3\lib\codecs.py"", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 15-16: invalid continuation byte
"
63,stefanoleone992_fifa-20-complete-player-dataset,../datasets\stefanoleone992_fifa-20-complete-player-dataset\players_15.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
64,stefanoleone992_fifa-20-complete-player-dataset,../datasets\stefanoleone992_fifa-20-complete-player-dataset\players_16.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
65,stefanoleone992_fifa-20-complete-player-dataset,../datasets\stefanoleone992_fifa-20-complete-player-dataset\players_17.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 341, in create_attributes_from_file_report
    add_accuracy_attributes(attributes_dict, feature_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 299, in add_accuracy_attributes
    dict['avg_gini_impurity_categ_features'] += feature_stats['statistics']['gini_impurity']
TypeError: unsupported operand type(s) for +=: 'float' and 'NoneType'
"
66,datatattle_covid-19-nlp-text-classification,../datasets\datatattle_covid-19-nlp-text-classification\Corona_NLP_test.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 339, in create_attributes_from_file_report
    add_consistency_attributes(attributes_dict, feature_stats, global_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 171, in add_consistency_attributes
    if feature_stats['data_type'] == 'integer':
TypeError: string indices must be integers
"
67,datatattle_covid-19-nlp-text-classification,../datasets\datatattle_covid-19-nlp-text-classification\Corona_NLP_train.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 501, in extract_file_attributes_to_df
    report, sample_size = create_profiler_report(data, profiler_options)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 321, in create_profiler_report
    sample_size = min(len(data.data), 500000)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 225, in __getattribute__
    returned = object.__getattribute__(self, name)
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\base_data.py"", line 70, in data
    self._load_data()
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\text_data.py"", line 82, in _load_data
    self._data = data_utils.read_text_as_list_of_strs(
  File ""C:\Users\radue\AppData\Roaming\Python\Python39\site-packages\dataprofiler\data_readers\data_utils.py"", line 399, in read_text_as_list_of_strs
    data = list(input_file)
  File ""C:\ProgramData\Anaconda3\lib\codecs.py"", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc2 in position 4761: invalid continuation byte
"
68,andrewmvd_data-analyst-jobs,../datasets\andrewmvd_data-analyst-jobs\DataAnalyst.csv,"Traceback (most recent call last):
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 504, in extract_file_attributes_to_df
    attribute_dict = create_attributes_from_file_report(data, report)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 339, in create_attributes_from_file_report
    add_consistency_attributes(attributes_dict, feature_stats, global_stats)
  File ""D:\meng-code\kaggle_data\attribute_extraction\attribute_extraction.py"", line 171, in add_consistency_attributes
    if feature_stats['data_type'] == 'integer':
TypeError: string indices must be integers
"
